// <auto-generated />
using System;
using BulkUpload.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkUpload.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkUpload.DataModel.Inventory.InvStockReceiveTemp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("AITPer")
                        .HasColumnType("float");

                    b.Property<double?>("AITValue")
                        .HasColumnType("float");

                    b.Property<double>("ATPer")
                        .HasColumnType("float");

                    b.Property<double?>("ATVPer")
                        .HasColumnType("float");

                    b.Property<double?>("ATVValue")
                        .HasColumnType("float");

                    b.Property<double?>("ATValue")
                        .HasColumnType("float");

                    b.Property<double?>("ActualQty")
                        .HasColumnType("float");

                    b.Property<string>("BOMNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BankAccountsId")
                        .HasColumnType("int");

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BillofEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CDPer")
                        .HasColumnType("float");

                    b.Property<double?>("CDValue")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ChallanDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChallanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallanRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ConvRate")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("Create_User")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edit_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("Edit_User")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("FreeQty")
                        .HasColumnType("float");

                    b.Property<string>("HSCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoRefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PortId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductGroup")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseLedgerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Qty")
                        .HasColumnType("float");

                    b.Property<double?>("RDPer")
                        .HasColumnType("float");

                    b.Property<double?>("RDValue")
                        .HasColumnType("float");

                    b.Property<double?>("Rate")
                        .HasColumnType("float");

                    b.Property<double?>("Rebate")
                        .HasColumnType("float");

                    b.Property<double?>("RebatePer")
                        .HasColumnType("float");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SD")
                        .HasColumnType("float");

                    b.Property<double?>("SD_Rate")
                        .HasColumnType("float");

                    b.Property<double?>("StockClosinigBalValue")
                        .HasColumnType("float");

                    b.Property<double?>("StockClosinigBalance")
                        .HasColumnType("float");

                    b.Property<double?>("StockOpiningBalValue")
                        .HasColumnType("float");

                    b.Property<double?>("StockOpiningBalance")
                        .HasColumnType("float");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierLedgerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<double?>("TotalConvAmount")
                        .HasColumnType("float");

                    b.Property<double?>("TotalPriceIncVAT")
                        .HasColumnType("float");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<double?>("VAT")
                        .HasColumnType("float");

                    b.Property<bool>("VATStatus")
                        .HasColumnType("bit");

                    b.Property<string>("VAT_AccountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("VAT_Rate")
                        .HasColumnType("float");

                    b.Property<bool?>("VDS_Applicable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Inv_StockReceive_Temp");
                });
#pragma warning restore 612, 618
        }
    }
}
